# .travis.yml
# https://travis-ci.org/neomantra/gcs-static-webserver
# Copyright (c) 2020 Neomantra Corp
#
# Travis Environment Variables:
#   DOCKER_ORG
#   DOCKER_USERNAME
#   DOCKER_PASSWORD
#

sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker image 
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_ORG/gcs-static-webserver:$TRAVIS_COMMIT .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker tag $DOCKER_ORG/gcs-static-webserver:$TRAVIS_COMMIT $DOCKER_ORG/gcs-static-webserver:latest &&
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker push $DOCKER_ORG/gcs-static-webserver:$TRAVIS_COMMIT &&
          docker push $DOCKER_ORG/gcs-static-webserver:latest ;
        fi
